name: Jitsi Web build and deploy

on:
  push:
     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: namespace-profile-default
    strategy:
      fail-fast: false
      matrix:
        git-ref: [
          "stable/jitsi-meet_10532",
          "stable/jitsi-meet_10431",
          "stable/jitsi-meet_10314",
          "stable/jitsi-meet_10184",
          "stable/jitsi-meet_10169",
          "stable/jitsi-meet_10133",
          "stable/jitsi-meet_10078",
          "stable/jitsi-meet_10073",
          "stable/jitsi-meet_10008",
          "stable/jitsi-meet_9955",
          "stable/jitsi-meet_9909",
          "stable/jitsi-meet_9823",
          "stable/jitsi-meet_9779",
          "stable/jitsi-meet_9753",
          "stable/jitsi-meet_9646",
          "stable/jitsi-meet_9584",
          "stable/jitsi-meet_9457",
          "stable/jitsi-meet_9364",
          "stable/jitsi-meet_9258",
          "stable/jitsi-meet_9220",
          "stable/jitsi-meet_9164",
          "stable/jitsi-meet_9111",
          "stable/jitsi-meet_9078",
          "stable/jitsi-meet_8960",
          "stable/jitsi-meet_8922",
          "stable/jitsi-meet_8719",
          "stable/jitsi-meet_8615",
          "stable/jitsi-meet_8319",
          "stable/jitsi-meet_8252",
          "stable/jitsi-meet_8218",
          "stable/jitsi-meet_8194",
          "stable/jitsi-meet_8138",
          "stable/jitsi-meet_8133",
          "stable/jitsi-meet_8127",
          "stable/jitsi-meet_8044",
          "stable/jitsi-meet_7882",
          "stable/jitsi-meet_7830",
          "stable/jitsi-meet_7648",
          "stable/jitsi-meet_7577",
          "stable/jitsi-meet_7439",
          "stable/jitsi-meet_7416",
          "stable/jitsi-meet_7287",
          "stable/jitsi-meet_7210",
          "stable/jitsi-meet_7001",
          "stable/jitsi-meet_6865",
          "stable/jitsi-meet_6826"
        ]
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: jitsi/jitsi-meet
        ref: ${{ matrix.git-ref }}
        path: jitsi-repo
      
    - name: Set up Node.js LTS
      uses: actions/setup-node@v5
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      working-directory: jitsi-repo
      run: npm i

    - name: Modify index.html
      working-directory: jitsi-repo
      run: |
        sed -i 's|<script><!--#include virtual="/interface_config.js" --></script>|<script src="interface_config.js"></script>|' index.html
        sed -i 's|<script><!--#include virtual="/config.js" --></script>|<script src="/config.js"></script>|' index.html
        cat ../override-config.js >> config.js

    - name: Build
      working-directory: jitsi-repo
      run: |
        make
        make source-package
        tar -xvjf jitsi-meet.tar.bz2
        
    # - name: Upload Build
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: website-zip
    #     path: jitsi-repo/jitsi-meet.tar.bz2

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      continue-on-error: true
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy jitsi-repo/jitsi-meet --project-name='ccjm' --branch=${{ matrix.git-ref }}

    # - name: Setup upterm session
    #   uses: owenthereal/action-upterm@v1
