name: Jitsi Web build and deploy

on:
  push:
     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: namespace-profile-default
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        path: main-repo

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: jitsi/jitsi-meet
        ref: stable/jitsi-meet_9364
      
    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm i

    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1

    - name: Modify index.html
      run: |
        sed -i 's|<script><!--#include virtual="/interface_config.js" --></script>|<script src="interface_config.js"></script>|' index.html
        sed -i 's|<script><!--#include virtual="/config.js" --></script>|<script src="/config.js"></script>|' index.html
        cat ./main-repo/override-config.js >> config.js

    - name: Build
      run: |
        make
        make source-package

    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
